version: '3'
services:
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./config:/etc/krakend
    ports:
      - "7081:8080"
      - "7091:8090"
#    environment:
#      - FC_ENABLE=1
#      - FC_SETTINGS=./settings/dev.json
#      - FC_PARTIALS=./partials
#      - FC_OUT=.      