version: '3'
services:
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./config:/etc/krakend
    environment:
      FC_ENABLE: 1
      FC_PARTIALS: "/etc/krakend/partials"
      FC_SETTINGS: "/etc/krakend/settings"
    ports:
      - "7081:8080"
      - "7091:8090"
    command: run -c /etc/krakend/krakend-full-flow.json
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
