version: '3'
services:
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./config:/etc/krakend
    environment:
      FC_ENABLE: 1
      FC_PARTIALS: "/etc/krakend/partials"
      FC_SETTINGS: "/etc/krakend/settings"
    ports:
      - "7081:8080"
      - "7091:8090"
    command: run -c /etc/krakend/krakend.json
    restart: on-failure
    networks:
      - microservices_network
      - zitadel_network
      - whatsapp_network
      - incidence_backend_default

networks:
  microservices_network:
    driver: bridge
  zitadel_network:
    external: true
  whatsapp_network:
    external: true
  incidence_backend_default:
    external: true